version: "3"
services:

  proxy:
    image: nginx:1.15-alpine
    volumes:
      - ./config/proxy/nginx.conf:/etc/nginx/conf.d/default.conf:ro
    ports:
      - "8080:80"

  db:
    image: postgres:12.2-alpine@sha256:9ea72265275674225b1eaa2ae897dd244028af4ee7ef6e4e89fe474938e0992e
    environment:
      - POSTGRES_USER=demo
      - POSTGRES_PASSWORD=demo
      - ALEXANDRIA_DB_PASSWORD=alexandria
      - EMEIS_DB_PASSWORD=emeis
      - CALUMA_DB_PASSWORD=caluma
    volumes:
      - ./config/db_setup/init-db.sh:/docker-entrypoint-initdb.d/init-db.sh:ro
      - dbdata:/var/lib/postgresql/data

  emeis:
    image: ghcr.io/projectcaluma/emeis:1.2.2
    depends_on:
      - db
    environment:
      - DATABASE_HOST=db
      - SECRET_KEY=demo
      - ALLOWED_HOSTS=*
      - DATABASE_PASSWORD=emeis
      - DATABASE_USER=emeis
      - ENV=production
      - ALLOW_ANONYMOUS_WRITE=true
      - LANGUAGES=de,en
      - VISIBILITY_CLASSES=
      - PERMISSION_CLASSES=

  alexandria:
    image: ghcr.io/projectcaluma/alexandria:2.2.0
    volumes:
        - "./config/alexandria/initial_data.json:/app/initial_data.json"
    depends_on:
      - db
      - minio
    environment:
      - DATABASE_HOST=db
      - SECRET_KEY=demo
      - ALLOWED_HOSTS=*
      - DATABASE_PASSWORD=alexandria
      - DATABASE_USER=alexandria
      - ENV=production
      - ALLOW_ANONYMOUS_WRITE=true
      - LANGUAGES=de,en
      - VISIBILITY_CLASSES=
      - PERMISSION_CLASSES=

  minio:
    image: minio/minio:latest
    volumes:
      - minio_data:/data
    ports:
      - "9000:9000"
    environment:
      - MINIO_ACCESS_KEY=minio
      - MINIO_SECRET_KEY=minio123
      - MINIO_NOTIFY_WEBHOOK_ENABLE_ALEXANDRIA=on
      - MINIO_NOTIFY_WEBHOOK_ENDPOINT_ALEXANDRIA=http://alexandria:8000/api/v1/hook
    command: server data

  mc:
    image: minio/mc:latest@sha256:43282b6ff47d3b6386c7b522e651af2492fef75e996302c9f10ee7a352e23748
    restart: on-failure
    environment:
      - MINIO_ACCESS_KEY=minio
      - MINIO_SECRET_KEY=minio123
    entrypoint: >
      /bin/sh -c "
      mc config host add dc-minio http://minio:9000 $${MINIO_ACCESS_KEY} $${MINIO_SECRET_KEY} --api S3v4;
      mc mb dc-minio/alexandria-media;
      mc event add dc-minio/alexandria-media arn:minio:sqs::ALEXANDRIA:webhook --event put;
      mc event list dc-minio/alexandria-media;
      mc admin trace --all --verbose dc-minio;"
    depends_on:
      - minio

  caluma:
    image: ghcr.io/projectcaluma/caluma:9.3.0
    depends_on:
      - db
    environment:
      - ENV=development
      - DATABASE_HOST=db
      - DATABASE_USER=caluma
      - DATABASE_PASSWORD=caluma
      - SECRET_KEY=caluma
      - ALLOWED_HOSTS=*
      - STATIC_ROOT=""
    volumes:
      - ./config/caluma/:/app/setup/

volumes:
  dbdata:
  minio_data:
  node_modules:

