name: Publish Ember Docker
on:
  push:
    branches:
      - main
env:
  ember-dir: ./ember

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: checkout branch
      uses: actions/checkout@v2

    - name: Install dependencies
      run: yarn install
      working-directory: ${{env.ember-dir}}

    - name: Build App
      run: yarn build
      working-directory: ${{env.ember-dir}}

    - name: Login to Dockerhub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKERHUB_USER }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Publish to Docker Hub
      uses: docker/build-push-action@v2.2.0
      with:
        context: ./ember/
        tags: projectcaluma/caluma-portal-demo:latest
